// Generated by CoffeeScript 1.6.2
(function() {
  var Sybil,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.exports = {};

  String.prototype.escapeBase64 = function() {
    return this.replace(/\//, "*");
  };

  String.prototype.unescapeBase64 = function() {
    return this.replace(/\*/, "/");
  };

  $(function() {
    return window.sybil = new Sybil;
  });

  Sybil = (function(_super) {
    __extends(Sybil, _super);

    function Sybil() {
      var _this = this;

      this.rssArr = [];
      this.feeds = {};
      window.TemplateManager = new Leaf.TemplateManager();
      window.TemplateManager.use("rss-list", "rss-list-item", "feed-list", "feed-list-item");
      window.TemplateManager.on("ready", function(templates) {
        _this.templates = templates;
        _this.init();
        Sybil.__super__.constructor.call(_this, document.body);
        return console.log(_this.rssList.node);
      });
      window.TemplateManager.start();
    }

    Sybil.prototype.init = function() {
      this.router = new Router();
      this.rssList = new RssList();
      this.feedList = new FeedList();
      this.rssList.sync();
      this.router.goto(window.location.hash);
      return this.common = exports;
    };

    return Sybil;

  })(Leaf.Widget);

}).call(this);
